name: Nieuws Script

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4.2.2

      - name: Python installeren
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.12'

      - name: Packages installeren
        run: pip install requests beautifulsoup4 lxml

      - name: Nieuws ophalen
        run: python script.py

      - name: Archief terugpushen naar GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add news.json
          git commit -m "update $(date +'%Y-%m-%d %H:%M UTC')" || echo "Niets nieuw"
          git push origin main --force